# Generated by Django 3.0.2 on 2020-02-17 04:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_rssfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 4, 39, 15, 249333, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
