# Generated by Django 2.2.10 on 2020-03-07 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='file_type',
            new_name='article_count',
        ),
    ]
