# Generated by Django 2.2.10 on 2020-03-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_auto_20200307_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
