# Generated by Django 2.2.10 on 2020-03-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_author_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_slug',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
